accent = "#00e3ff"
cursor = "#00e3ff"
foreground = "#ffffff"
background = "#000000"
selection_foreground = "#f0f0f0"
selection_background = "#005367"

color0 = "#3C486D"
color1 = "#14ab00"
color2 = "#f540fb"
color3 = "#ffa412"
color4 = "#30d0ff"
color5 = "#c89dc1"
color6 = "#a3bfd1"
color7 = "#620090"
color8 = "#1163a6"
color9 = "#faaaa9"
color10 = "#97b8d2"
color11 = "#f7dc9c"
color12 = "#40d0f0"
color13 = "#ead7e7"
color14 = "#ffad14"
color15 = "#ffcead"