accent = "#00e3ff"
cursor = "#00e3ff"
foreground = "#ffffff"
background = "#00101e"
selection_foreground = "#f0f0f0"
selection_background = "#005367"

color0 = "#3C486D"
color1 = "#ED5B5A"
color2 = "#92a593"
color3 = "#c26100"
color4 = "#009cd9"
color5 = "#c89dc1"
color6 = "#a3bfd1"
color7 = "#620090"
color8 = "#6d7db6"
color9 = "#faaaa9"
color10 = "#c4cfc4"
color11 = "#f7dc9c"
color12 = "#c2c4f0"
color13 = "#ead7e7"
color14 = "#dfeaf0"
color15 = "#ffcead"
