accent = "#00e3ff"
cursor = "#00e3ff"
foreground = "#ffffff"
background = "#000000"
selection_foreground = "#f0f0f0"
selection_background = "#005367"
color0 = "#000000"
color1 = "#a80006"
color2 = "#06bb00"
color3 = "#ffa412"
color4 = "#30c0ff"
color5 = "#cc44be"
color6 = "#20d2ff"
color7 = "#620090"
color8 = "#505050"
color9 = "#ff0000"
color10 = "#1eff00"
color11 = "#efcb29"
color12 = "#30d0ff"
color13 = "#f540fb"
color14 = "#30d0ff"
color15 = "#ffffff"
