# primary
background = #00101e
foreground = #ffffff
cursor-color = #00e3ff
cursor-text = #0e091d

# normal colors
palette = 0=#3C486D
palette = 1=#14ab00
palette = 2=#f540fb
palette = 3=#ffa412
palette = 4=#30d0ff
palette = 5=#c89dc1
palette = 6=#a3bfd1
palette = 7=#620090
# bright colors
palette = 8=#1163a6
palette = 9=#faaaa9
palette = 10=#97b8d2
palette = 11=#f7dc9c
palette = 12=#40d0f0
palette = 13=#ead7e7
palette = 14=#ffad14
palette = 15=#ffcead